/**
 * ULPIN round-trip tests.
 *
 * Run with:  node --test lib/ulpin.test.ts
 * (Node strips the type annotations natively; there is no build step.)
 *
 * These also pin the encoding that db/02_functions.sql's ulpin_fmt() mirrors --
 * if the two ever diverge, identifiers generated by the pipeline stop parsing
 * in the UI, so the format is asserted literally rather than by construction.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import {
  codesOf, floorCode, generate, levelOf, parentOf, parse, parseFloorCode,
  parseUnitSlot, prefixFor, unitSlot, DEFAULT_CODES,
} from './ulpin.ts';

/** A second project, in a different state and district. */
const TS_HYD = { state: 'TS', district: 'HYD', scheme: '3D26' };

test('generates right-truncated identifiers at each level', () => {
  assert.equal(generate(42), 'AP-VSP-3D26-0042');
  assert.equal(generate(42, 7), 'AP-VSP-3D26-0042-007');
  assert.equal(generate(42, 7, 0), 'AP-VSP-3D26-0042-007-00');
  assert.equal(generate(42, 7, 5), 'AP-VSP-3D26-0042-007-05');
  assert.equal(generate(42, 7, -2), 'AP-VSP-3D26-0042-007-B2');
  assert.equal(generate(42, 7, 5, 3), 'AP-VSP-3D26-0042-007-05-03');
});

test('matches the SQL encoding for the cases ulpin_fmt covers', () => {
  // Fixed expectations, verified against a live postgres ulpin_fmt() call.
  assert.equal(generate(42), 'AP-VSP-3D26-0042');
  assert.equal(generate(42, 7), 'AP-VSP-3D26-0042-007');
  assert.equal(generate(42, 7, 0), 'AP-VSP-3D26-0042-007-00');
  assert.equal(generate(42, 7, -2), 'AP-VSP-3D26-0042-007-B2');
  assert.equal(generate(42, 7, 5, 3), 'AP-VSP-3D26-0042-007-05-03');
});

/**
 * The same parity assertion for a SECOND project.
 *
 * ulpin_fmt() gained three code arguments so that a project outside
 * Visakhapatnam mints identifiers in its own state and district. The two
 * implementations have to agree for those too, or an identifier generated by
 * the pipeline stops parsing in the UI -- which is the whole reason this file
 * asserts the format literally rather than by construction.
 *
 * Fixed expectations, verified against:
 *   SELECT ulpin_fmt(42, 7, 5, 3, 'TS', 'HYD', '3D26');
 */
test('matches the SQL encoding for a second project (TS/HYD)', () => {
  assert.equal(generate(42, undefined, undefined, undefined, TS_HYD),
    'TS-HYD-3D26-0042');
  assert.equal(generate(42, 7, undefined, undefined, TS_HYD),
    'TS-HYD-3D26-0042-007');
  assert.equal(generate(42, 7, 0, undefined, TS_HYD), 'TS-HYD-3D26-0042-007-00');
  assert.equal(generate(42, 7, -2, undefined, TS_HYD), 'TS-HYD-3D26-0042-007-B2');
  assert.equal(generate(42, 7, 5, 3, TS_HYD), 'TS-HYD-3D26-0042-007-05-03');
});

/**
 * The defaults are what make this change invisible to the demo project.
 *
 * Every ULPIN in data/api/siripuram/ was minted before ulpin_fmt() and
 * generate() took codes at all. If a code-less call ever stopped producing
 * the AP-VSP-3D26 prefix, 384 buildings, 325 parcels, 1,810 floors and 6,438
 * units would all change identifier at once.
 */
test('omitting the codes still mints the demo project prefix', () => {
  assert.deepEqual(DEFAULT_CODES, { state: 'AP', district: 'VSP', scheme: '3D26' });
  assert.equal(prefixFor(), 'AP-VSP-3D26');
  assert.equal(prefixFor(TS_HYD), 'TS-HYD-3D26');
  for (const args of [[1], [325], [42, 7], [42, 7, 0], [42, 7, -1], [42, 7, 5, 3]]) {
    const [p, b, f, u] = args as [number, number?, number?, number?];
    assert.ok(generate(p, b, f, u).startsWith('AP-VSP-3D26-'));
    assert.equal(generate(p, b, f, u), generate(p, b, f, u, DEFAULT_CODES));
  }
});

test('parcel numbering restarts per project; the prefix keeps them apart', () => {
  // Parcel 0001 exists in both projects, which is the point -- it is the
  // state/district prefix that makes the two identifiers different.
  const ap = generate(1, 1, 0, 1);
  const ts = generate(1, 1, 0, 1, TS_HYD);
  assert.notEqual(ap, ts);
  assert.deepEqual(parse(ap), parse(ts, TS_HYD));
  assert.deepEqual(codesOf(ap), DEFAULT_CODES);
  assert.deepEqual(codesOf(ts), TS_HYD);
});

test('a second project round-trips at every level', () => {
  const cases: [number, number?, number?, number?][] = [
    [1], [325], [42, 7], [42, 7, 0], [42, 7, 12], [42, 7, -1], [42, 7, -2, 4],
    [9999, 999, 99, 99],
  ];
  for (const [p, b, f, u] of cases) {
    const id = generate(p, b, f, u, TS_HYD);
    const back = parse(id, TS_HYD);
    assert.ok(back, `failed to parse ${id}`);
    assert.equal(back.parcel, p);
    assert.equal(back.building, b);
    assert.equal(back.floor, f);
    assert.equal(back.unit, u);
    assert.equal(generate(back.parcel, back.building, back.floor, back.unit, TS_HYD), id);
    // Walking up must not silently relabel the identifier as AP-VSP.
    const up = parentOf(id);
    if (up !== null) assert.ok(up.startsWith('TS-HYD-3D26-'), up);
  }
});

test('a strict parse rejects the codes of another project', () => {
  // The default is the demo project's codes, so this still rejects exactly
  // what it always rejected -- including XX-VSP below.
  assert.equal(parse('TS-HYD-3D26-0042'), null);
  assert.equal(parse('AP-VSP-3D26-0042', TS_HYD), null);
  // 'any' accepts whatever well-formed prefix it finds, which is what a
  // viewer already showing a project's data needs.
  assert.deepEqual(parse('TS-HYD-3D26-0042', 'any'), { parcel: 42 });
  assert.equal(levelOf('TS-HYD-3D26-0042-007-05-03'), 'unit');
  // Shape still has to hold, whatever the codes.
  assert.equal(parse('T-HYD-3D26-0042', 'any'), null);
  assert.equal(parse('TS-HYD-3D26-42', 'any'), null);
  assert.equal(codesOf('not-a-ulpin'), null);
});

test('round-trips through parse at every level', () => {
  const cases: [number, number?, number?, number?][] = [
    [1], [325], [42, 7], [42, 7, 0], [42, 7, 12], [42, 7, -1], [42, 7, -2, 4],
    [9999, 999, 99, 99],
  ];
  for (const [p, b, f, u] of cases) {
    const id = generate(p, b, f, u);
    const back = parse(id);
    assert.ok(back, `failed to parse ${id}`);
    assert.equal(back.parcel, p);
    assert.equal(back.building, b);
    assert.equal(back.floor, f);
    assert.equal(back.unit, u);
    assert.equal(generate(back.parcel, back.building, back.floor, back.unit), id);
  }
});

test('floor codes survive a round trip, basements included', () => {
  for (const level of [-9, -2, -1, 0, 1, 9, 12, 99]) {
    assert.equal(parseFloorCode(floorCode(level)), level);
  }
  assert.equal(floorCode(0), '00');
  assert.equal(floorCode(-1), 'B1');
  assert.equal(floorCode(7), '07');
});

test('reports the addressed level', () => {
  assert.equal(levelOf(generate(1)), 'parcel');
  assert.equal(levelOf(generate(1, 2)), 'building');
  assert.equal(levelOf(generate(1, 2, 3)), 'floor');
  assert.equal(levelOf(generate(1, 2, 3, 4)), 'unit');
});

test('walks up the hierarchy', () => {
  const unit = generate(42, 7, 5, 3);
  assert.equal(parentOf(unit), 'AP-VSP-3D26-0042-007-05');
  assert.equal(parentOf(parentOf(unit)!), 'AP-VSP-3D26-0042-007');
  assert.equal(parentOf(parentOf(parentOf(unit)!)!), 'AP-VSP-3D26-0042');
  assert.equal(parentOf(generate(42)), null);
});

test('rejects identifiers that are not ours', () => {
  for (const bad of [
    '', 'not-a-ulpin', 'AP-VSP-3D26', 'AP-VSP-3D26-42', 'AP-VSP-3D26-0042-7',
    'XX-VSP-3D26-0042', 'AP-VSP-3D26-0042-007-5', 'AP-VSP-3D26-0042-007-05-3',
    'AP-VSP-3D26-0042-007-XX',
  ]) {
    assert.equal(parse(bad), null, `should have rejected ${JSON.stringify(bad)}`);
  }
});

test('accepts lower case and surrounding whitespace', () => {
  assert.deepEqual(parse('  ap-vsp-3d26-0042-007-b2  '), {
    parcel: 42, building: 7, floor: -2,
  });
});

// ---------------------------------------------------------------------------
// Typed unit slots
// ---------------------------------------------------------------------------

/**
 * THE REGRESSION THIS FILE EXISTED TO CATCH AND DID NOT.
 *
 * The unit group used to be `(\d{2})`, so a slot of any other width failed to
 * parse. Every one of Sampath Skyline's 80 flats is numbered by storey --
 * '101' on level 1, '2004' on level 20 -- so none of them parsed, which
 * silently dropped UlpinCard's segment breakdown and made parentOf() return
 * null for every flat in the building. generate() was always right; only the
 * reader disagreed, which is exactly the drift the header comment warns about.
 */
test('parses the storey-numbered flats the demo tower actually ships', () => {
  assert.deepEqual(parse('AP-VSP-3D26-9999-001-01-101'), {
    parcel: 9999, building: 1, floor: 1,
    unit: 101, unitSlot: '101', unitKind: 'flat',
  });
  assert.deepEqual(parse('AP-VSP-3D26-9999-001-20-2004'), {
    parcel: 9999, building: 1, floor: 20,
    unit: 2004, unitSlot: '2004', unitKind: 'flat',
  });
  assert.equal(levelOf('AP-VSP-3D26-9999-001-01-101'), 'unit');
  assert.equal(parentOf('AP-VSP-3D26-9999-001-01-101'), 'AP-VSP-3D26-9999-001-01');
});

test('encodes a unit slot for every kind', () => {
  assert.equal(unitSlot('flat', 3), '03');
  assert.equal(unitSlot('flat', 101), '101');
  assert.equal(unitSlot('flat', 2004), '2004');
  assert.equal(unitSlot('retail', 1), 'R01');
  assert.equal(unitSlot('anchor', 9), 'R09');
  assert.equal(unitSlot('parking', 101), 'P101');
  assert.equal(unitSlot('circulation', 2), 'C02');
  assert.equal(unitSlot('atrium', 1), 'C01');
  assert.equal(unitSlot('elevator'), 'EV');
  assert.equal(unitSlot('stair'), 'ST');
  assert.equal(unitSlot('plant'), 'PL');
});

/** A flat has no prefix to carry, so it cannot be named without an ordinal. */
test('a flat slot requires an ordinal', () => {
  assert.throws(() => unitSlot('flat'), /needs an ordinal/);
});

test('generates typed identifiers, still seven groups', () => {
  const shop = generate(165, 1, 0, unitSlot('retail', 1));
  assert.equal(shop, 'AP-VSP-3D26-0165-001-00-R01');
  assert.equal(shop.split('-').length, 7);
  assert.equal(generate(9999, 1, -1, unitSlot('parking', 101)),
    'AP-VSP-3D26-9999-001-B1-P101');
  assert.equal(generate(9999, 1, -2, unitSlot('elevator')),
    'AP-VSP-3D26-9999-001-B2-EV');
  assert.equal(generate(9999, 1, 20, unitSlot('stair')),
    'AP-VSP-3D26-9999-001-20-ST');
});

test('reads the kind back out of a typed identifier', () => {
  const kindOf = (u: string) => parse(u, 'any')?.unitKind;
  assert.equal(kindOf('AP-VSP-3D26-0165-001-00-R01'), 'retail');
  assert.equal(kindOf('AP-VSP-3D26-9999-001-B1-P101'), 'parking');
  assert.equal(kindOf('AP-VSP-3D26-0165-001-00-C01'), 'circulation');
  assert.equal(kindOf('AP-VSP-3D26-9999-001-B2-EV'), 'elevator');
  assert.equal(kindOf('AP-VSP-3D26-9999-001-05-ST'), 'stair');
  assert.equal(kindOf('AP-VSP-3D26-0165-001-00-01'), 'flat');
});

/**
 * A shaft is one volume per level with no ordinal, so `unit` is absent while
 * `unitSlot` is present. Consumers deciding "is this a unit?" must read
 * unitSlot -- reading `unit` would classify a lift core as a floor.
 */
test('a core slot carries no ordinal but is still unit level', () => {
  const p = parse('AP-VSP-3D26-9999-001-B2-EV');
  assert.deepEqual(p, {
    parcel: 9999, building: 1, floor: -2, unitSlot: 'EV', unitKind: 'elevator',
  });
  assert.equal(p!.unit, undefined);
  assert.equal(levelOf('AP-VSP-3D26-9999-001-B2-EV'), 'unit');
  assert.equal(parentOf('AP-VSP-3D26-9999-001-B2-EV'), 'AP-VSP-3D26-9999-001-B2');
});

test('every typed identifier round-trips through generate', () => {
  for (const u of [
    'AP-VSP-3D26-0165-001-00-R01', 'AP-VSP-3D26-9999-001-B1-P101',
    'AP-VSP-3D26-9999-001-B2-EV', 'AP-VSP-3D26-9999-001-20-ST',
    'AP-VSP-3D26-0165-001-00-C01', 'AP-VSP-3D26-9999-001-01-101',
    'AP-VSP-3D26-0042-007-05-03',
  ]) {
    const p = parse(u, 'any')!;
    assert.equal(
      generate(p.parcel, p.building, p.floor, p.unitSlot, codesOf(u)!), u,
    );
  }
});

test('parseUnitSlot rejects malformed slots', () => {
  // A prefix that takes an ordinal, without one; one that does not, with one.
  for (const bad of ['R', 'P', 'C', 'EV01', 'ST99', 'XX', 'X01', '3', '', 'R1']) {
    assert.equal(parseUnitSlot(bad), null,
      `should have rejected ${JSON.stringify(bad)}`);
  }
});

/** The widening must not have loosened what a ULPIN is. */
test('still rejects unit slots that are not ours', () => {
  for (const bad of [
    'AP-VSP-3D26-0042-007-05-3',     // one digit
    'AP-VSP-3D26-0042-007-XX',       // not a kind prefix
    'AP-VSP-3D26-0042-007-05-X01',
    'AP-VSP-3D26-0042-007-05-R1',    // ordinal too short
    'AP-VSP-3D26-0042-007-05-EV01',  // core with an ordinal
    'AP-VSP-3D26-0042-007-05-00001', // five digits
  ]) {
    assert.equal(parse(bad, 'any'), null,
      `should have rejected ${JSON.stringify(bad)}`);
  }
});

/**
 * Parity with the SQL side of the typed slot.
 *
 * Same discipline as the ulpin_fmt() tests above, for the same reason: the
 * seeders mint these in SQL and the viewer reads them in TypeScript, so a
 * divergence would show up as a shop that cannot be picked rather than as a
 * failing build.
 *
 * Fixed expectations, verified against a live postgres:
 *   SELECT ulpin_fmt_slot(165,  1,  0, unit_slot('retail', 1));
 *   SELECT ulpin_fmt_slot(9999, 1, -1, unit_slot('parking', 101));
 *   SELECT ulpin_fmt_slot(9999, 1, -2, unit_slot('elevator'));
 *   SELECT ulpin_fmt_slot(9999, 1, 20, unit_slot('stair'));
 *   SELECT ulpin_fmt_slot(165,  1,  0, unit_slot('atrium', 1));
 *   SELECT ulpin_fmt_slot(9999, 1,  1, unit_slot('flat', 101));
 *   SELECT ulpin_fmt_slot(42, 7, 5, unit_slot('flat', 3), 'TS','HYD','3D26');
 */
test('matches the SQL encoding for typed unit slots', () => {
  assert.equal(generate(165, 1, 0, unitSlot('retail', 1)),
    'AP-VSP-3D26-0165-001-00-R01');
  assert.equal(generate(9999, 1, -1, unitSlot('parking', 101)),
    'AP-VSP-3D26-9999-001-B1-P101');
  assert.equal(generate(9999, 1, -2, unitSlot('elevator')),
    'AP-VSP-3D26-9999-001-B2-EV');
  assert.equal(generate(9999, 1, 20, unitSlot('stair')),
    'AP-VSP-3D26-9999-001-20-ST');
  assert.equal(generate(165, 1, 0, unitSlot('atrium', 1)),
    'AP-VSP-3D26-0165-001-00-C01');
  assert.equal(generate(9999, 1, 1, unitSlot('flat', 101)),
    'AP-VSP-3D26-9999-001-01-101');
  assert.equal(generate(42, 7, 5, unitSlot('flat', 3), TS_HYD),
    'TS-HYD-3D26-0042-007-05-03');
});
